### ISSUE TITLE
README.md instructions to start frontend don't work

### ISSUE THREAD

**Issue by eswenson1** [kyledinh/zio-petclinic-scala-3#9]
README.md says:

Run the frontend in a separate **Terminal 2**
```
open http://localhost:3000
make frontend-up
```

However, the Makefile has this target:

```
frontend-up:
        @open http://localhost:3000
        @cd js-javascript && yarn exec vite
```
       
Note that the Makefile already includes the "open http://localhost:3000".  However, this make target doesn't work because there is no `js-javascript` subdirectory.  There is a `js-frontend` directory, however.  The Makefile should be updated.

**Comment by kyledinh** [comment]
Cool!! Thanks, I'll update it.
